apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      nodeSelector:
        app: orkis-backend
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_NAME}:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: websocket
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "1024Mi"
          volumeMounts:
            - mountPath: /app/share/jobs
              name: jobs-pvc
            - mountPath: /app/share/sqlite
              name: sqlite-pvc
            - mountPath: /app/share/summary
              name: chat-summary-pvc
            - mountPath: /app/storage
              name: orkis-backend-pvc
      volumes:
        - name: jobs-pvc
          persistentVolumeClaim:
            claimName: orkis-jobs-data-archive-pvc
        - name: chat-summary-pvc
          persistentVolumeClaim:
            claimName: chat-summary-pvc
        - name: sqlite-pvc
          persistentVolumeClaim:
            claimName: sqlite-database-pvc
        - name: orkis-backend-pvc
          persistentVolumeClaim:
            claimName: orkis-backend-storage-pvc
