export const BEAN_SCAN_TYPES = Object.freeze({
  APPLICATION_CONTEXT: Symbol("APPLICATION_CONTEXT"),
  CONFIG: Symbol("CONFIG"),
  APPLICATION: Symbol("APPLICATION"),
  CONTROLLER: Symbol("CONTROLLER"),
  SERVICE: Symbol("SERVICE"),
  COMPONENT: Symbol("COMPONENT"),
  INTERCEPTOR: Symbol("INTERCEPTOR"),
  REQUEST_MAPPING: Symbol("REQUEST_MAPPING"),
  DAO: Symbol("DAO"),
  REPOSITORY: Symbol("REPOSITORY"),
  DATABASE_CONFIG: Symbol("DATABASE_CONFIG")
});

export const BEAN_STATES = Object.freeze({
  SCAN_SUCCEED: Symbol("SCAN_SUCCEED"),
  SINGLETON_GENERATED: Symbol("SINGLETON_GENERATED"),
  SINGLETON_ADDED: Symbol("SINGLETON_ADDED"),
  REQUEST_ADDED: Symbol("REQUEST_ADDED"),
  NEW_ADDED: Symbol("NEW_ADDED")
});

export const SCOPE_TYPES = Object.freeze({
  REQUEST_SCOPE: Symbol(0),
  SINGLETON_SCOPE: Symbol(1),
  PROTOTYPE_SCOPE: Symbol(2)
});
