apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${KUBE_NAMESPACE}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      nodeSelector:
        app: orkis-ai
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_NAME}:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: orkis-ai-config
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "3.5"
              memory: "7Gi"
          volumeMounts:
            - mountPath: /app/storage/orkis-ai
              name: shared-data
            - mountPath: /app/storage/sqlite
              name: sqlite
            - mountPath: /app/storage/chat_summary
              name: chat-summary
            - mountPath: /app/TEMP
              name: sqlite-local-temp
            - mountPath: /dev/shm
              name: dshm

      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
        - name: shared-data
          persistentVolumeClaim:
            claimName: orkis-ai-python-shared-pvc
        - name: sqlite
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: sqlite-database-pvc
        - name: chat-summary
          persistentVolumeClaim:
            claimName: chat-summary-pvc
        - name: sqlite-local-temp
          persistentVolumeClaim:
            claimName: orkis-ai-temp-pvc
