apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-summary-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-static
  volumeName: chat-summary-pv
