apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orkis-jobs-data-archive-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-static
  volumeName: orkis-jobs-data-archive-pv
