apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-database-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-static
  volumeName: sqlite-database-pv
