apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-database-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 172.25.1.129
    path: /share_ee5038c0_4304_4915_a277_a5ea082e01f1/orkis-sqlite-database-pvc
  claimRef:
    namespace: orkis
    name: sqlite-database-pvc
