apiVersion: v1
kind: Service
metadata:
  name: orkis-postgres-svc
  namespace: orkis
spec:
  type: ClusterIP
  ports:
    - name: postgresport
      port: 47432
      targetPort: 5432
  selector:
    db-engine: postgres
