apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-local-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-postgres
  volumeName: postgres-local-pv
