apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: orkis
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      db-engine: postgres
  template:
    metadata:
      labels:
        db-engine: postgres
    spec:
      nodeSelector:
        app: orkis-database
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17-alpine
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-logs
              mountPath: /var/lib/postgresql/data/pg_log
            - name: postgres-config-volume
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-local-pvc
        - name: postgres-logs
          emptyDir: {}
        - name: postgres-config-volume
          configMap:
            name: postgres-config
            items:
              - key: postgresql.conf
                path: postgresql.conf
