apiVersion: apps/v1
kind: Deployment
metadata:
  name: orkis-chat-redis
  namespace: orkis
  labels:
    app: orkis-chat-redis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: orkis-chat-redis
  template:
    metadata:
      labels:
        app: orkis-chat-redis
    spec:
      nodeSelector:
        app: orkis-database
      containers:
        - name: orkis-chat-redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
