apiVersion: apps/v1
kind: Deployment
metadata:
  name: orkis-session-redis
  namespace: orkis
  labels:
    app: orkis-session-redis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: orkis-session-redis
  template:
    metadata:
      labels:
        app: orkis-session-redis
    spec:
      nodeSelector:
        app: orkis-database
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
