services:
  orkis-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: orkis-front:latest
    container_name: orkis-front
    ports:
      - "5173:80"
    networks:
      - orkis-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  orkis-network:
    external: true