apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-global-config
  namespace: cicd
data:
  BUILD_OUTPUT_DIR: "/var/jenkins_build_output"
  org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud plugin="kubernetes@4384.v1b_6367f393d9">
      <garbageCollection>
        <timeout>900</timeout>  <!-- 기존 300에서 900초로 증가 -->
      </garbageCollection>
      <maxRequestsPerHost>32</maxRequestsPerHost>
      <waitForPodSec>600</waitForPodSec>
      <podRetention class="org.csanchez.jenkins.plugins.kubernetes.pod.retention.Default"/> <!-- Never 대신 Default로 변경 -->
    </org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud>
