nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.0.cjs
enableGlobalCache: false
npmScopes:
  orkis:
    npmRegistryServer: "https://git.orkis.kr/api/v4/projects/6/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "glpat-uqKyizhccMZFziudhqqc"
