services:
  orkis-backend:
    volumes:
      - ../orkis-core/src:/app/node_modules/@orkis/core/src
# services:
#   orkis-backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     container_name: orkis-backend-dev
#     ports:
#       - "8080:8080" # HTTP API
#       - "8081:8081" # WebSocket
#       - "9229:9229" # Node.js debugger
#     volumes:
#       # 소스코드 마운트 (실시간 반영)
#       - ./src:/app/src
#       - ./resources:/app/resources
#       - ./share:/app/share
#       # node_modules는 컨테이너 내부 것 사용
#       - /app/node_modules
#       - ./package.json:/app/package.json
#       # orkis-core 필요한 파일만 마운트 (node_modules 제외)
#       - ../orkis-core/lib:/app/node_modules/@orkis/core/lib
#       - ../orkis-core/package.json:/app/node_modules/@orkis/core/package.json
#       - ../orkis-core/src:/app/node_modules/@orkis/core/src
#     env_file: ./resources/dev.env
#     environment:
#       - WS_PORT=8081
#     restart: unless-stopped
