apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orkis-backend-storage-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-static
  volumeName: orkis-backend-storage-pv
