apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orkis-ai-temp-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: orkis-ai-temp-pv
