apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orkis-ai-python-shared-pvc
  namespace: orkis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-static
  volumeName: orkis-ai-python-shared-pv
