enableGlobalCache: false
nodeLinker: node-modules
npmScopes:
  orkis:
    npmAlwaysAuth: true
    npmAuthToken: glpat-uqKyizhccMZFziudhqqc
    npmRegistryServer: "https://git.orkis.kr/api/v4/projects/6/packages/npm/"
