nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.0.cjs

npmScopes:
  orkis:
    npmRegistryServer: "https://git.orkis.kr/api/v4/projects/6/packages/npm/"
    npmPublishRegistry: "https://git.orkis.kr/api/v4/projects/6/packages/npm/"
    npmAuthToken: "${NPM_TOKEN}"
