apiVersion: v1
kind: Pod
metadata:
  name: docker-test
  namespace: cicd
spec:
  containers:
  - name: docker
    image: docker:dind
    command:
      - dockerd
    securityContext:
      privileged: true
  restartPolicy: Never