controller:
  kind: DaemonSet

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  nodeSelector:
    app: ingress

  tolerations: []

  service:
    enabled: false

  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  ingressClass: nginx

  admissionWebhooks:
    enabled: false

  watchIngressWithoutClass: false

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    proxy-body-size: "2g"

  metrics:
    enabled: false

defaultBackend:
  enabled: false
