# NFS subdir external provisioner
# 기존 KT Cloud NAS (172.25.1.129) 를 동적 PVC로 자동 프로비저닝
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: ktc-nfs-provisioner
  labels:
    app: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 172.25.1.129
            - name: NFS_PATH
              value: /share_ee5038c0_4304_4915_a277_a5ea082e01f1
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.25.1.129
            path: /share_ee5038c0_4304_4915_a277_a5ea082e01f1
